### ISSUE TITLE
How To Install

### ISSUE THREAD

**Issue by karansoi** [soldag/python-pwmled#2]
I have HASSOS13.3 installed on my RPi4 + 4Gig.
I have added this in my config.yaml file
`# Example configuration.yaml entry
light:
  - platform: rpi_gpio_pwm
    leds:
      - name: Lightstrip Cupboard
        driver: gpio
        pins: [17]
        type: simple`
This is the error reported in the log
`Logger: homeassistant.components.light
Source: components/rpi_gpio_pwm/light.py:127
Integration: Light (documentation, issues)
First occurred: May 9, 2020, 8:53:22 PM (1 occurrences)
Last logged: May 9, 2020, 8:53:22 PM

Error while setting up rpi_gpio_pwm platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 443, in _async_add_entity
    await entity.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/rpi_gpio_pwm/light.py", line 127, in async_added_to_hass
    is_on=self._is_on, brightness=_from_hass_brightness(self._brightness)
  File "/usr/local/lib/python3.7/site-packages/pwmled/led/__init__.py", line 76, in set
    self._update_pwm()
  File "/usr/local/lib/python3.7/site-packages/pwmled/led/__init__.py", line 85, in _update_pwm
    self._driver.set_pwm(values)
  File "/usr/local/lib/python3.7/site-packages/pwmled/driver/__init__.py", line 52, in set_pwm
    self._set_pwm(self._to_raw_pwm(values))
  File "/usr/local/lib/python3.7/site-packages/pwmled/driver/gpio.py", line 34, in _set_pwm
    self._pi.set_PWM_dutycycle(self._pins[i], raw_values[i])
  File "/usr/local/lib/python3.7/site-packages/pigpio.py", line 1396, in set_PWM_dutycycle
    self.sl, _PI_CMD_PWM, user_gpio, int(dutycycle)))
  File "/usr/local/lib/python3.7/site-packages/pigpio.py", line 977, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
AttributeError: 'NoneType' object has no attribute 'send'`
Request help on this issue

**Comment by karansoi** [comment]
I installed he pigpio daemon and got th pwmled working.
